enableImmutableInstalls: false

enableInlineBuilds: false

enableTelemetry: false

httpTimeout: 60000

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  datalayer:
    npmAlwaysAuth: true
    npmAuthToken: ghs_ns7WZk63NPmVl1e63w4mId1Q4Dbt0p4T2cSL
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@lerna/legacy-package-management@*":
    dependencies:
      "@lerna/child-process": "*"
      js-yaml: "*"
      rimraf: "*"
    peerDependencies:
      nx: "*"
