import { CellIcon, CollaborateIcon, CommandsIcon, ConsoleIcon, DashboardIcon, DialogIcon, DoubleDownIcon, DoubleUpIcon, FastForwardIcon, FastRewindIcon, FileBrowserIcon, IpyWidgetsIcon, LuminoIcon, NotebookIcon, OrganisationIcon, OutputIcon, SchoolIcon, SettingsIcon, StudentIcon, TerminalIcon } from "../react/outline";
import { AcademicCapIcon, DaskIcon, DatalayerIcon, DatalayerGreenIcon, JupyterHubServiceIcon, JupyterHubIcon, JupyterLabIcon, JupyterKernelGatewayIcon, JupyterKernelIcon, JupyterKernelProvisionerIcon, JupyterIcon, JupyterNameIcon, JupyterContentIcon, JupyterMystIcon, JupyterNotebookIcon, JupyterServerIcon, JupyterTraitletIcon, KubernetesIcon, KubernetesNodeIcon, KubernetesPodIcon, KubernetesServiceIcon, PyTorchIcon, ReactIcon, TensorFlowIcon, TwitterIcon, WebRtcIcon } from "../react/solid";

const icons = {
  AcademicCap: AcademicCapIcon,
  Collaborate: CollaborateIcon,
  Cell: CellIcon,
  Console: ConsoleIcon,
  Commands: CommandsIcon,
  Dask: DaskIcon,
  Dashboard: DashboardIcon,
  Datalayer: DatalayerIcon,
  DatalayerGreen: DatalayerGreenIcon,
  Dialog: DialogIcon,
  DoubleDown: DoubleDownIcon,
  DoubleUp: DoubleUpIcon,
  FastForward: FastForwardIcon,
  FastRewind: FastRewindIcon,
  FileBrowser: FileBrowserIcon,
  IpyWidgets: IpyWidgetsIcon,
  Jupyter: JupyterIcon,
  JupyterContent: JupyterContentIcon,
  JupyterName: JupyterNameIcon,
  JupyterLab: JupyterLabIcon,
  JupyterHub: JupyterHubIcon,
  JupyterHubService: JupyterHubServiceIcon,
  JupyterKernel: JupyterKernelIcon,
  JupyterKernelGateway: JupyterKernelGatewayIcon,
  JupyterKernelProvisioner: JupyterKernelProvisionerIcon,
  JupyterMyst: JupyterMystIcon,
  JupyterNotebook: JupyterNotebookIcon,
  JupyterServer: JupyterServerIcon,
  JupyterTraitlet: JupyterTraitletIcon,
  Kubernetes: KubernetesIcon,
  KubernetesNode: KubernetesNodeIcon,
  KubernetesPod: KubernetesPodIcon,
  KubernetesService: KubernetesServiceIcon,
  Lumino: LuminoIcon,
  Notebook: NotebookIcon,
  Organisation: OrganisationIcon,
  Output: OutputIcon,
  PyTorch: PyTorchIcon,
  React: ReactIcon,
  School: SchoolIcon,
  Settings: SettingsIcon,
  Student: StudentIcon,
  TensorFlow: TensorFlowIcon,
  TerminalIcon: TerminalIcon,
  Twitter: TwitterIcon,
  WebRTC: WebRtcIcon,
};

export default icons;
