import {
  AcademicCapIcon,
  AnacondaIcon,
  BooksIcon,
  CellIcon,
  CloudIcon,
  CloudUploadIcon,
  CollaborateIcon,
  CommandsIcon,
  ConsoleIcon,
  DashboardIcon,
  DaskIcon,
  DatalayerGreenIcon,
  DatalayerIcon,
  DialogIcon,
  DoubleDownIcon,
  DoubleUpIcon,
  EditorIcon,
  FastForwardIcon,
  FastRewindIcon,
  FileBrowserIcon,
  IpyWidgetsIcon,
  JupyterContentIcon,
  JupyterHubIcon,
  JupyterHubServiceIcon,
  JupyterIcon,
  JupyterKernelGatewayIcon,
  JupyterKernelIcon,
  JupyterKernelProvisionerIcon,
  JupyterLabIcon,
  JupyterMoonsIcon,
  JupyterMystIcon,
  JupyterNamedIcon,
  JupyterNotebookIcon,
  JupyterServerIcon,
  JupyterTraitletIcon,
  KubernetesIcon,
  KubernetesNodeIcon,
  KubernetesPodIcon,
  KubernetesServiceIcon,
  LaptopIcon,
  LuminoIcon,
  MicrosoftAzureIcon,
  MicrosoftIcon,
  NotebookIcon,
  OpenStackIcon,
  OrganisationIcon,
  OutputIcon,
  OvhCloudIcon,
  PyTorchIcon,
  QuansightIcon,
  ReactIcon,
  SchoolIcon,
  SettingsIcon,
  StudentIcon,
  TensorFlowIcon,
  TerminalIcon,
  TwitterIcon,
  VsCodeIcon,
  WebRtcIcon,
} from "../react";

const icons = {
  AcademicCap: AcademicCapIcon,
  Anaconda: AnacondaIcon,
  Books: BooksIcon,
  Cell: CellIcon,
  Cloud: CloudIcon,
  CloudUpload: CloudUploadIcon,
  Collaborate: CollaborateIcon,
  Commands: CommandsIcon,
  Console: ConsoleIcon,
  Dashboard: DashboardIcon,
  Dask: DaskIcon,
  Datalayer: DatalayerIcon,
  DatalayerGreen: DatalayerGreenIcon,
  Dialog: DialogIcon,
  DoubleDown: DoubleDownIcon,
  DoubleUp: DoubleUpIcon,
  Editor: EditorIcon,
  FastForward: FastForwardIcon,
  FastRewind: FastRewindIcon,
  FileBrowser: FileBrowserIcon,
  IpyWidgets: IpyWidgetsIcon,
  Jupyter: JupyterIcon,
  JupyterContent: JupyterContentIcon,
  JupyterHub: JupyterHubIcon,
  JupyterHubService: JupyterHubServiceIcon,
  JupyterKernel: JupyterKernelIcon,
  JupyterKernelGateway: JupyterKernelGatewayIcon,
  JupyterKernelProvisioner: JupyterKernelProvisionerIcon,
  JupyterLab: JupyterLabIcon,
  JupyterMoons: JupyterMoonsIcon,
  JupyterMyst: JupyterMystIcon,
  JupyterNamed: JupyterNamedIcon,
  JupyterNotebook: JupyterNotebookIcon,
  JupyterServer: JupyterServerIcon,
  JupyterTraitlet: JupyterTraitletIcon,
  Kubernetes: KubernetesIcon,
  KubernetesNode: KubernetesNodeIcon,
  KubernetesPod: KubernetesPodIcon,
  KubernetesService: KubernetesServiceIcon,
  Laptop: LaptopIcon,
  Lumino: LuminoIcon,
  Microsoft: MicrosoftIcon,
  MicrosoftAzure: MicrosoftAzureIcon,
  Notebook: NotebookIcon,
  OpenStack: OpenStackIcon,
  Organisation: OrganisationIcon,
  Output: OutputIcon,
  OvhCloud: OvhCloudIcon,
  PyTorch: PyTorchIcon,
  Quansight: QuansightIcon,
  React: ReactIcon,
  School: SchoolIcon,
  Settings: SettingsIcon,
  Student: StudentIcon,
  TensorFlow: TensorFlowIcon,
  Terminal: TerminalIcon,
  Twitter: TwitterIcon,
  VsCode: VsCodeIcon,
  WebRTC: WebRtcIcon,
};

export default icons;
