import { CellIcon, CollaborateIcon, ConsoleIcon, DoubleDownIcon, DoubleUpIcon, FastForwardIcon, FastRewindIcon, IPyWidgetsIcon, NotebookIcon, OrganisationIcon, OutputIcon, SchoolIcon, StudentIcon } from "../react/outline";
import { AcademicCapIcon, DaskIcon, DatalayerIcon, DatalayerDaskIcon, DatalayerGreenIcon, JupyterHubServiceIcon, JupyterHubIcon, JupyterLabIcon, JupyterKernelGatewayIcon, JupyterKernelIcon, JupyterKernelProvisionerIcon, JupyterIcon, JupyterMystIcon, JupyterServerIcon, JupyterTraitletIcon, KubernetesIcon, KubernetesNodeIcon, KubernetesPodIcon, KubernetesServiceIcon, PyTorchIcon, ReactIcon, TensorFlowIcon, TwitterIcon, WebRtcIcon } from "../react/solid";

const icons = {
  AcademicCap: AcademicCapIcon,
  Collaborate: CollaborateIcon,
  Cell: CellIcon,
  Console: ConsoleIcon,
  Dask: DaskIcon,
  Datalayer: DatalayerIcon,
  DatalayerDask: DatalayerDaskIcon,
  DatalayerGreen: DatalayerGreenIcon,
  DoubleDown: DoubleDownIcon,
  DoubleUp: DoubleUpIcon,
  FastForward: FastForwardIcon,
  FastRewind: FastRewindIcon,
  IPyWidgets: IPyWidgetsIcon,
  Jupyter: JupyterIcon,
  JupyterLab: JupyterLabIcon,
  JupyterHub: JupyterHubIcon,
  JupyterHubService: JupyterHubServiceIcon,
  JupyterKernel: JupyterKernelIcon,
  JupyterKernelGateway: JupyterKernelGatewayIcon,
  JupyterKernelProvisioner: JupyterKernelProvisionerIcon,
  JupyterMyst: JupyterMystIcon,
  JupyterServer: JupyterServerIcon,
  JupyterTraitlet: JupyterTraitletIcon,
  Kubernetes: KubernetesIcon,
  KubernetesNode: KubernetesNodeIcon,
  KubernetesPod: KubernetesPodIcon,
  KubernetesService: KubernetesServiceIcon,
  Notebook: NotebookIcon,
  Organisation: OrganisationIcon,
  Output: OutputIcon,
  PyTorch: PyTorchIcon,
  React: ReactIcon,
  School: SchoolIcon,
  Student: StudentIcon,
  TensorFlow: TensorFlowIcon,
  Twitter: TwitterIcon,
  WebRTC: WebRtcIcon,
};

export default icons;
